/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./components/About.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AuthorCRUD: typeof import('./components/AuthorCRUD.vue')['default']
    BookCRUD: typeof import('./components/BookCRUD.vue')['default']
    Components: typeof import('./components/HelloWorld.vue')['default']
    CreateForm: typeof import('./components/author/CreateForm.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    OrderCRUD: typeof import('./components/OrderCRUD.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StudentCRUD: typeof import('./components/StudentCRUD.vue')['default']
  }
}
